/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import com.sun.tools.javac.Main;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
//    @Test void someLibraryMethodReturnsTrue() {
//        Library classUnderTest = new Library();
//        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
//    }
Library testObject = new Library();
    @Test public void testRollMethod(){
        int[]arr = testObject.roll(6);
        assertEquals(6,arr.length);
    }

    @Test public void testContainsDuplicates(){
        int[] array1 = {1,2,3,4};
        int[] array2 = {1,1,2,3,3,4,5};
        assertTrue(testObject.containsDuplicates(array2));
        assertFalse(testObject.containsDuplicates(array1));
    }

    @Test public void testAverages(){
        int[]array1 = {1,2,3,4,5,9};
        int[]array2 = {};
        assertEquals(4,testObject.averages(array1));
        assertEquals(0,testObject.averages(array2));
    }

    @Test public void testLowestAverage() {
        int[][] Array={
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        int[] actValue=testObject.lowestAvg(Array);
        int[] expValue={55, 54, 60, 53, 59, 57, 61};
        assertArrayEquals(expValue,actValue);
    }

}
