/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.*;

public class Library {
//    public boolean someLibraryMethod() {
//        return true;
//    }

    public int[] roll (int num){
        if(num<0) {num= 0;}

        int[] randomArray = new int[num];
        Random randNum = new Random();

        for (int i= 0; i < num ; i++){
            int randomResult = randNum.nextInt(6)+1;
            randomArray[i]=randomResult;
        }
        return randomArray;
    }

    public boolean containsDuplicates (int [] array ) {
        Set<Integer> set = new HashSet<Integer>();
        for ( int i = 0; i < array.length; ++i ) {
            if ( set.contains( array[i])) {
                return true;
            }
            else {
                set.add(array[i]);
            }
        }
        return false;
    }
    public double averages (int [] array) {
        if(array.length==0) return 0;
        double total = 0;
        for( int i = 0 ; i < array.length ; i++){
            total = total + array[i];
        }
        double average = total / array.length;
        return average;
    }

    public int[] lowestAvg (int[][] arr){
        double currentAvg=0;
        double lowAvg=0;
        int lowestArray=0;

        lowAvg = averages(arr[0]);

        for(int i =1 ; i< arr.length; i++){

            currentAvg= averages(arr[i]);
            if(lowAvg>currentAvg){
                lowAvg=currentAvg;
                lowestArray=i;
            }

        }
        return arr[lowestArray];
    }

    public String weatherData(int[][] array) {
        int high = 0;
        int low = array[0][0];
        String outputTemp = "";

        Set<Integer> tempData = new HashSet<Integer>();

        for(int[] innerArr : array){
            for(int numb : innerArr){
                tempData.add(numb);
                if(numb > high)
                    high = numb;
                if(numb < low)
                    low = numb;
            }
        }

        for (int i = low; i <= high; i++) {
            if (!tempData.contains(i)) {
                outputTemp += "Never saw temperature: " + i + "\n";
            }
        }

        System.out.println("High: " + high);
        System.out.println("Low: " + low);
        System.out.println(outputTemp);
        return outputTemp;

        }

    public static String tally (List<String>  list) {
        HashSet<String> voteNames = new HashSet<String>(list);
        int counter = 0;
        int hightVotes = 0;

        String hightName = "";
        for (String name : voteNames) {
            for (int i = 0; i < list.size(); i++)
                if (list.get(i) == name)
                    counter++;
            if (counter > hightVotes) {
                hightVotes = counter;
                hightName = name;
            }
            counter = 0;
        }
        return hightName;
    }
    }

