/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.util.HashSet;
import java.util.Random;
import java.util.Set;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public int[] roll (int num){
        if(num<0) {num= 0;}

        int[] randomArray = new int[num];
        Random randNum = new Random();

        for (int i= 0; i < num ; i++){
            int randomResult = randNum.nextInt(6)+1;
            randomArray[i]=randomResult;
        }
        return randomArray;
    }

    public boolean containsDuplicates (int [] array ) {
        Set<Integer> set = new HashSet<Integer>();
        for ( int i = 0; i < array.length; ++i ) {
            if ( set.contains( array[i])) {
                return true;
            }
            else {
                set.add(array[i]);
            }
        }
        return false;
    }
}
