/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test public void restaurantTest(){
        Restaurant restaurant =new Restaurant("Brisket",4,"$$");
        assertEquals("Restaurant{name='Brisket', stars=4, price=$$, reviews=[]}",restaurant.toString());
        assertEquals("Brisket",restaurant.getName());
        assertEquals(4,restaurant.getStars());
        assertEquals("$$",restaurant.getPrice());
    }
    @Test public void restaurantTest2(){
        Restaurant restaurant =new Restaurant("Sufra",5,"$$$$");
        assertEquals("Restaurant{name='Sufra', stars=5, price=$$$$, reviews=[]}",restaurant.toString());
        assertEquals("Sufra",restaurant.getName());
        assertEquals(5,restaurant.getStars());
        assertEquals("$$$$",restaurant.getPrice());
    }

    @Test public  void  addReviewTest(){
        Restaurant restaurant =new Restaurant("Brisket",4,"$$");
        Review review=new Review("its a good restuarant","Ahmad",5);
        restaurant.addReview(review);
        assertEquals("Ahmad", restaurant.getReviews().get(0).getAuthor());
        assertEquals("its a good restuarant", restaurant.getReviews().get(0).getBody());
        assertEquals(5, restaurant.getReviews().get(0).getNumberOfStars());
    }

    @Test public  void  addReviewTest2(){
        Restaurant restaurant =new Restaurant("Sufra",5,"$$$$");
        Review review=new Review("its a good restuarant","Mahmoud",3);
        restaurant.addReview(review);
        assertEquals("Mahmoud", restaurant.getReviews().get(0).getAuthor());
        assertEquals("its a good restuarant", restaurant.getReviews().get(0).getBody());
        assertEquals(3, restaurant.getReviews().get(0).getNumberOfStars());
    }
}
