/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;


class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test public void testRollMethod(){
        int[]arr = testObject.roll(6);
        assertEquals(6,arr.length);
    }

    @Test public void testContainsDuplicates(){
        int[] array1 = {1,2,3,4};
        int[] array2 = {1,1,2,3,3,4,5};
        assertTrue(testObject.containsDuplicates(array2));
        assertFalse(testObject.containsDuplicates(array1));
    }



}
